language: node_js

node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile
  - git config --global user.name 'JounQin'
  - git config --global user.email 'admin@1stg.me'

before_script: greenkeeper-lockfile-update

script:
  - yarn lint
  - yarn build
  - 'if [[ $TRAVIS_BRANCH = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then yarn sync:push; fi'

after_script: greenkeeper-lockfile-upload
